version: '3.8'

services:
  koodaamo-web:
    container_name: koodaamo-web
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/www/html:/var/www/html
      - ./logs:/var/log/nginx
    networks:
      - koodaamo-web-network
    restart: unless-stopped

  cloudflared:
    container_name: koodaamo-web-cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}
    networks:
      - koodaamo-web-network
    depends_on:
      - koodaamo-web
    healthcheck:
      test: ['CMD', 'cloudflared', 'tunnel', 'status']
      interval: 10s
      timeout: 5s
      retries: 3
    command: tunnel run

networks:
  koodaamo-web-network:
